app:
  name: movie-info-service
  description : Welcome to my ${app.name}

server.port: 7082


management.endpoints.web.exposure.include: "*"

spring:
  profiles:
    active:
    - dev
  application:
    name: movie-info-service
  cloud:
    config:
      uri: 
      - https://github.com/gpandeya/confg-server

