app:
  name: movie-info-dev-service
  description : Welcome to my ${app.name}

server.port: 7082

moviedb:
  baseurl: http://api.themoviedb.org/3/movie/
  key: 41e19c74b05cc1baaa2038ac60abe0a7

management.endpoints.web.exposure.include: "*"